targets:
  $default:
    builders:
      build_web_compilers|entrypoint:
        options:
          compiler: dart2js
          dart2js_args:
      build_web_compilers|dart_source_cleanup:
        release_options:
          enabled: false
